services:
  postgres:
    container_name: smartbuy-postgres
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_USER: smartbuy
      POSTGRES_PASSWORD: smartbuy
      POSTGRES_DB: smartbuy
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
